site_name: SunSeaLucky's Note
theme:
    name: material
    features:
        - navigation.tabs
        - navigation.top
        - content.code.copy # Code Block Copy Button
    # ------ Dark and Light Mode ------
    palette:
        # Palette toggle for automatic mode
        - media: "(prefers-color-scheme)"
          toggle:
            icon: material/brightness-auto
            name: Switch to light mode

        # Palette toggle for light mode
        - media: "(prefers-color-scheme: light)"
          scheme: default 
          toggle:
            icon: material/brightness-7
            name: Switch to dark mode

        # Palette toggle for dark mode
        - media: "(prefers-color-scheme: dark)"
          scheme: slate
          toggle:
            icon: material/brightness-4
            name: Switch to system preference
    # ------ Dark and Light Mode ------

markdown_extensions:
    - pymdownx.highlight: # Code Block
        linenums: true        
        line_spans: __span
        pygments_lang_class: true
    - pymdownx.inlinehilite # Code Block
    - pymdownx.snippets # Code Block
    - pymdownx.superfences: # Mermaid
        custom_fences:
            - name: mermaid
              class: mermaid
              format: !!python/name:pymdownx.superfences.fence_code_format
    - pymdownx.arithmatex: # KaTeX
        generic: true
extra_javascript:
    - javascripts/katex.js
    - https://unpkg.com/katex@0/dist/katex.min.js
    - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js
extra_css:
    - https://unpkg.com/katex@0/dist/katex.min.css
    - css/style.css

nav:
    - 首页: index.md
    - 深度伪造: 
        - 笔记: deepfake/note/main.md
        - 实验: deepfake/experiment/main.md